name: barber_shop
description: "Basic for my Barber Shops"
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  image_cropper: ^8.0.2

  # Firebase
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6

  # Bloc
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  bloc: ^8.1.4

  # Custom Repository
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true